apiVersion: v1
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gitrepo-rs
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: git-backed-volume
  template: 
    metadata: 
      labels: 
        app: git-backed-volume
    spec:
      containers:
      - name: web-server
        image: nginx:alpine
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: html
        gitRepo:
          repository: https://github.com/prashdeep/kubia-website-example.git
          revision: master
          directory: .