apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: healthchecker
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata: 
      labels:
        app: ssd-monitor
    spec:
     nodeSelector:
       disk: ssd 
     containers:
       - name: sshchecker
         image: luksa/ssd-monitor
