apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: inventory-microservice-rs
spec: 
  replicas: 3
  selector:
    matchLabels: 
      app: inventory-microservice
  template: 
    metadata: 
      labels: 
        app: inventory-microservice
    spec:
      containers:
      - image: classpathio/inventory-microservice:1.0.0
        name: inventory-microservice-container
        ports:
        - containerPort: 8080