apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-volume
spec:
  containers:
  - image: nginx:apline
    name: webserver
    volumeMounts:
        - name: configuration
          mountPath: /etc/nginx/conf.d
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: configuration
        configMap:
          name: nginx-config