apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-volume
spec:
  containers:
  - image: nginx:alpine
    name: webserver-config
    volumeMounts:
    - name: configuration
      mountPath: /etc/nginx/conf.d
      readOnly: true
    ports:
    - containerPort: 82
      protocol: TCP
  volumes:
  - name: configuration
    configMap:
      name: nginx-configuration
