apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: order-ingress
  annotations:
#    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - classpath.com
    secretName: tls-secret
  rules:
  - host: classpath.com
    http:
      paths:
        - path: /order
          backend:
            serviceName: order-service
            servicePort: 80
        - path: /inventory
          backend:
            serviceName: inventory-service
            servicePort: 81
